### ISSUE TITLE
some-name is not working

### ISSUE THREAD

**Issue by EdinsonNM** [KacperKozak/project-snippets#2]
hello, I have a problem when I using some-name

![image](https://user-images.githubusercontent.com/1783460/103237233-f8f65980-4914-11eb-8755-5231b5a45be9.png)

**Comment by KacperKozak** [comment]
Hi, yeah my bad, `some - name` is a JS expression. I will fix this in a minute.

**Comment by KacperKozak** [comment]
Ok, I found that you can use `locals` global to access this kind of variable names.
For example:
```
import <%= locals['some-name'] %>.scss
```

**Comment by KacperKozak** [comment]
And for now, I think it is the best way to do that. 
Also, I added a warning about this in docs, thanks! :)

**Comment by EdinsonNM** [comment]
Great, this does work well. Your library is great, thanks!
